[package]
name = "r-unic/array"
description = "Array class, featuring many familiar methods from JavaScript and more."
version = "0.3.1"
license = "MIT"
authors = ["Runic"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Iter = "chriscerie/iter@^0.1"