[package]
name = "r-unic/array"
description = "Array class, featuring many familiar methods from JavaScript and more."
version = "0.2.7"
license = "MIT"
authors = ["Runic"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"